name: Release Docker Image

on:
  push:
    branches:
    - master
  release:
    types: [published]

jobs:

  release:
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout code
      uses: actions/checkout@master

    - name: Set environment variables
      run: |
        if [[ "${{ github.event_name }}" == "release" ]]; then
          tag_name="${{ github.event.release.tag_name }}"
        else
          tag_name="latest"
        fi
        echo "::set-env name=DOCKER_TAG::apiconsole/apiconsole:${tag_name}"

    - name: Build image
      run: docker build -t "${DOCKER_TAG}" .

    - name: Login to Registries
      run: docker login -u apiconsole --password-stdin <<< "${{ secrets.DOCKER_HUB_TOKEN }}"

    - name: Push to Docker Hub
      run: docker push "${DOCKER_TAG}"
